# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Classify the mixed normal data using Rcpp
#' @description The EM algorithm is used to classify data from binary or ternary positive mixing models Rcpp
#' @param data Data set for clustering, length \code{n}
#' @param K EM Indicates the maximum number of iterations of the algorithm
#' @param iters Whether to output EM number of iterations, the default value is T
#' @return A list consisting of the following sections:
#' \describe{
#'   \item{\code{label}}{Data of length \code{n} consisting of 0 or 1 or 2, used to mark the classification category}
#'   \item{\code{param}}{Estimates of the mean and standard deviation of the corresponding two or three normal distributions, as well as estimates of the mixed proportions}
#' }
#' @examples
#' \dontrun{
#' data(data_mix2)
#' norm_clusC(data_mix2,10)
#' }
#' 
#' @export
norm_clusC <- function(data, K, iters = TRUE) {
    .Call('_SA23204182_norm_clusC', PACKAGE = 'SA23204182', data, K, iters)
}

